### ISSUE TITLE
Hole fixing algorithm is extremely slow (200+ hours)

### ISSUE THREAD

**Issue by mon** [svg2mod/svg2mod#18]
I have an SVG I exported from OpenSCAD. It contains only line segments. Admittedly, this is a very complex shape.
![image](https://user-images.githubusercontent.com/3398021/99544147-b2e9d400-29ff-11eb-8879-3e4f9704a2da.png)

After printing `Inlining 11 segments...` the converter freezes. By throwing a sneaky `from tqdm import trange as range` in `svg2mod.py` I can see the hole finding/fixing algorithm is running very slowly. The outer loop with 6065 iterations to go is expected to take 236 hours. The inner loop is running between 40 and 70 iterations per second, with 6064 iterations per loop.

See attached:
[artwork_pcb.zip](https://github.com/svg2mod/svg2mod/files/5560745/artwork_pcb.zip)

svg2shenzhen also has issues with this file, my current process involves manually exporting and stacking using bitmap2component and a 1200dpi PNG export from the SVG.

**Comment by Sodium-Hydrogen** [comment]
This is a known shortcoming. I recently patched the original hole parsing to fix a bug to support multiple holes. I left the original algorithm until I could find time to completely overhaul this. A more permanent fix will be coming, but until this you could try simplifying the shape in inkscape into curves then running svg2mod.

**Comment by mon** [comment]
Excellent! I'm so used to curves being unsupported by hobbyist projects, I didn't even realise simplify would work. This can be easily automated, so I'll add it to my process and see how the speed improves.

**Comment by Sodium-Hydrogen** [comment]
Just a note. When you use the `-p` flag if you set the value to low you will still get similarly long times, but kicad stopped showing me finer details after it got small enough. So you'll still have the trade off of smooth curves vs time to process, but I would trend higher than 1 for `-p` just to keep things pretty fast to convert with still keeping mostly fine details

**Comment by Sodium-Hydrogen** [comment]
Also I am looking to add support for drill holes and that could also make something like your project significantly faster to parse because it wouldn't have to care about properly converting multiple holes.

**Comment by mon** [comment]
On the drill holes - since kicad (or maybe my manufacturer?) automatically "fixes" the gerbers so holes are clear of other elements, I could just remove them from the artwork export. The only thing it helps with is in pcbnew itself, especially where silk covers holes in the 3D preview.

Still haven't got around to testing and fiddling with the inkscape smoothing factor and `-p`, but will take a look this weekend.

**Comment by Sodium-Hydrogen** [comment]
It's been a while since this pull request was opened, but once #43 is finalized, tested, and merged it should take runtime down to around 2 seconds for the attached file.

**Comment by mon** [comment]
This is wicked sick, thanks! This will simplify my toolchain significantly
