### ISSUE TITLE
Suggestion: Force-layer option

### ISSUE THREAD

**Issue by matthijskooijman** [svg2mod/svg2mod#21]
Currently, an SVG must be modified to let the layer names in the SVG match the KiCad layer names. Often, however, you just want to convert some logo to a single layer (just copper, or just silkscreen, or maybe duplicate all SVG content on multiple layers like copper and soldermask). To simplify this process without having to modify the SVG, it could be useful to have a commandline option to specify the layer(s) to use, rather than looking at the SVG layer names.

**Comment by Sodium-Hydrogen** [comment]
To clarify for my understanding, this would introduce a feature where it would treat all layers in the svg as a single layer and output a kicad module with only the specified layer meaning multi layer images would be compressed into a single layer even if they overlap?

This is an interesting idea. As of now this tool only supports svgs output in inkscape's format. This could add some basic support for non-inkscape svgs.

**Comment by matthijskooijman** [comment]
> To clarify for my understanding, this would introduce a feature where it would treat all layers in the svg as a single layer and output a kicad module with only the specified layer meaning multi layer images would be compressed into a single layer even if they overlap?

Yup, that's what I had in mind.
