### ISSUE TITLE
Feature: Split unrelated filled subpaths inside the same path

### ISSUE THREAD

**Issue by matthijskooijman** [svg2mod/svg2mod#26]
When you have multiple disjoint subpaths within a single path, they get converted to a single filled polygon. I.e. this single path:

![image](https://user-images.githubusercontent.com/194491/107821150-44a57b00-6d7c-11eb-84a5-051582fcb435.png)

Gets converted to this:

![image](https://user-images.githubusercontent.com/194491/107821527-f17ff800-6d7c-11eb-80e0-8078938aaf40.png)

Note the connecting line.

Keeping multiple subpaths of a single path inside a single polygon in the output is important, when those subpaths are inside each others (i.e. holes). In this case, the code tries hard to find a connection between both subpaths that only crosses filled areas, so the connection line is not visible. However, in cases like these, where the two paths are entirely disjoint, such a connection is not possible, so an extra line is visible.

In these cases, it would be nice if the output could just have two separate polygons instead of just one.

This is of course a gold-plating feature, since a very easy (and probably reasonably obvious) workaround is to "break apart" the path in inkscape.

This seems to be relate to #18, which is about the hole fixing algorithm that would probably be involved here.

**Comment by Sodium-Hydrogen** [comment]
#33 fixes this.
