### ISSUE TITLE
Current version appears to not generate anything with default options

### ISSUE THREAD

**Issue by gkelly** [svg2mod/svg2mod#5]
As installed via `pip3 install git+https://github.com/svg2mod/svg2mod`, when running `svg2mod -i dt-logo.svg` in the examples directory the output is:

```
(module svg2mod (layer F.Cu) (tedit 5F134CF1)
  (attr virtual)
  (descr "Imported from dt-logo.svg")
  (tags svg2mod)
  (fp_text reference svg2mod (at 0 -3.048) (layer F.SilkS) hide
    (effects (font (size 1.524 1.524) (thickness 0.3048)))
  )
  (fp_text value G*** (at 0 3.048) (layer F.SilkS) hide
    (effects (font (size 1.524 1.524) (thickness 0.3048)))
  )
)
```

If run using `svg2mod -i dt-logo.svg --format legacy` then the corresponding `dt-logo.mod` is generated and looks reasonable, but isn't usable from Kicad 5.1.

**Comment by davidcutting42** [comment]
@gkelly can you post the dt-logo.svg file?

**Comment by jdthorpe** [comment]
This is merely because the example is not a good example.  specifically, the properly named layers are empty (contain no  path elements)  and the layers with content don't match the naming schema.

**Comment by Sodium-Hydrogen** [comment]
I've updated the svg to work with the current version so the default args should work on the example now
