### ISSUE TITLE
Missing polygons and grouped objects

### ISSUE THREAD

**Issue by UnforeseenOcean** [svg2mod/svg2mod#52]
### The problem

On converted footprint, some parts of the object being converted are missing. This may include the entire design, or just anything around the center point.
![IMG1660624119](https://user-images.githubusercontent.com/11834016/184797946-765a22c8-4868-4b81-b7db-e0da23a65cfa.png)

### Version

1.1

### Command line

svg2mod -i 07.svg -c -f 1.5 --debug -o 07.kicad_mod

### Debug output

```txt
C:\Users\Torbjorn\Desktop\SVG\New>svg2mod -i 07.svg -c -f 1.5 --debug -o 07.kicad_mod 
Parsing SVG...
No handler for element {http://www.w3.org/2000/svg}metadata
No handler for element {http://www.w3.org/2000/svg}defs
No handler for element {http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd}namedview
No handler for element {http://www.w3.org/2000/svg}title
No handler for element {http://www.w3.org/2000/svg}polygon
Document scaling: 1.0 units per pixel
Found SVG layer: F.SilkS
  Detailed names: [F.SilkS]
Writing module file: 07.kicad_mod
  Inlining 1 segments...
  Writing Path with 14 points
```

### Sample file and additional information

[Test.zip](https://github.com/svg2mod/svg2mod/files/9347904/Test.zip)

`SVGs` folder contains the original files, and `Compare To` folder contains the converted files that are coming out with bad results, as well as some that come out with good results.

This time the flow of the process was as follows:
1. Aseprite - Export - SVG
2. Bring to Illustrator - Pathfinder - Join (Combine) (This combines the millions of squares into one or more solid polygons)
3. Illustrator - Object - Path - Simplify Path (Set angle to 45 degrees, used Straight Line option, this gets rid of the errant anchor points caused by many squares on the Aseprite SVG file)
4. Export each object as SVG (default setting - SVG 1.1)
5. Open each file in Inkscape 0.92.4 - Assign Solid Fill - Assign No Stroke - Make layer `F.SilkS` - Move to layer `F.SilkS`
6. Save, repeat for all files
7. Use svg2mod to complete the process

**Comment by Sodium-Hydrogen** [comment]
FWI while I work on fully fixing this bug you can use
```
pip install git+https://github.com/sodium-hydrogen/svg2mod
```
to install the developmental versions.

Also you can use the `--force F.SilkS` to remove the need for inkscape when you are targeting a single layer for a svg.
